name: "Test"
on:
  push:
    branches: [main, "release/**"]
  workflow_dispatch:
  pull_request:
    branches: [main, "release/**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - run: yarn run test
